default_stages: [commit]

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
  - id: detect-private-key
  - id: check-merge-conflict
- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.29.0
  hooks:
    - id: yamllint
      args: [--strict]
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.37.0
  hooks:
  - id: markdownlint
