- id: validate-shell-snippets
  name: Validate shell inline script snippets
  description: This hook performs shellcheck on inline scripts in AZDO pipeline yamls.
  entry: /bin/validate-shell-snippets
  language: docker
  types: [yaml]
- id: validate-powershell-snippets
  name: Validate powershell inline script snippets
  description: This hook performs PSScriptAnalyzer on inline scripts in AZDO pipeline yamls.
  entry: /bin/validate-pwsh-snippets
  language: docker
  types: [yaml]
- id: validate-shell-snippets-docker-latest
  name: Validate shell inline script snippets with latest docker
  description: This hook performs shellcheck on inline scripts in AZDO pipeline yamls.
  language: docker_image
  entry: --entrypoint /bin/validate-shell-snippets ghcr.io/krisgeus/inline-shell-check:latest
  types: [yaml]
- id: validate-shell-snippets-docker-release
  name: Validate shell inline script snippets with released docker
  description: This hook performs shellcheck on inline scripts in AZDO pipeline yamls.
  language: docker_image
  entry: --entrypoint /bin/validate-shell-snippets ghcr.io/krisgeus/inline-shell-check:v2.0.2
  types: [yaml]
- id: validate-powershell-snippets-docker-latest
  name: Validate powershell inline script snippets with latest docker
  description: This hook performs PSScriptAnalyzer on inline powershell scripts in AZDO pipeline yamls.
  language: docker_image
  entry: --entrypoint /bin/validate-pwsh-snippets ghcr.io/krisgeus/inline-shell-check:latest
  types: [yaml]
- id: validate-powershell-snippets-docker-release
  name: Validate powershell inline script snippets with released docker
  description: This hook performs PSScriptAnalyzer on inline powershell scripts in AZDO pipeline yamls.
  language: docker_image
  entry: --entrypoint /bin/validate-pwsh-snippets ghcr.io/krisgeus/inline-shell-check:v2.0.2
  types: [yaml]
