- id: validate-shell-snippets
  name: Validate shell inline script snippets
  description: This hook performs shellcheck on inline scripts in AZDO pipeline yamls.
  entry: validate-shell-snippets
  language: docker
  types: [yaml]
- id: validate-shell-snippets-docker-latest
  name: Validate shell inline script snippets with latest docker
  description: This hook performs shellcheck on inline scripts in AZDO pipeline yamls.
  language: docker_image
  entry: ghcr.io/krisgeus/inline-bash-check:latest
  types: [yaml]
- id: validate-shell-snippets-docker-release
  name: Validate shell inline script snippets with released docker
  description: This hook performs shellcheck on inline scripts in AZDO pipeline yamls.
  language: docker_image
  entry: ghcr.io/krisgeus/inline-bash-check:v2.0.1
  types: [yaml]
- id: validate-powershell-snippets-docker-latest
  name: Validate powershell inline script snippets with latest docker
  description: This hook performs PSScriptAnalyzer on inline powershell scripts in AZDO pipeline yamls.
  language: docker_image
  entry: ghcr.io/krisgeus/inline-pwsh-check:latest
  types: [yaml]
- id: validate-powershell-snippets-docker-release
  name: Validate shell inline script snippets with released docker
  description: This hook performs PSScriptAnalyzer on inline powershell scripts in AZDO pipeline yamls.
  language: docker_image
  entry: ghcr.io/krisgeus/inline-pwsh-check:v2.0.1
  types: [yaml]
