default_stages: [commit]

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
  - id: detect-private-key
  - id: check-merge-conflict
- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.29.0
  hooks:
    - id: yamllint
      args: [--strict]
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.37.0
  hooks:
  - id: markdownlint

- repo: https://github.com/hadolint/hadolint
  rev: v2.12.0
  hooks:
    - id: hadolint-docker

- repo: local
  hooks:
    - id: powershell-script-checker
      name: powershell-script-checker
      language: docker_image
      entry: --user root --entrypoint pwsh --rm cypher0n3/psscriptanalyzer-docker:latest
      args:
        - -Command
        - /src/PSScriptAnalyzer-wrapper.ps1
        - -Check
      types_or: [powershell]
      pass_filenames: true
    - id: powershell-script-formatter
      name: powershell-script-formatter
      language: docker_image
      entry: --user root --entrypoint pwsh --rm cypher0n3/psscriptanalyzer-docker:latest
      args:
        - -Command
        - /src/PSScriptAnalyzer-wrapper.ps1
        - -Format
      types_or: [powershell]
      pass_filenames: true

- repo: https://github.com/koalaman/shellcheck-precommit
  rev: v0.9.0
  hooks:
    - id: shellcheck
