default_stages: [commit]

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
  - id: detect-private-key
  - id: check-merge-conflict
- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.29.0
  hooks:
    - id: yamllint
      args: [--strict]
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.37.0
  hooks:
  - id: markdownlint

- repo: https://github.com/hadolint/hadolint
  rev: v2.12.0
  hooks:
    - id: hadolint-docker

- repo: https://github.com/melmorabity/pre-commit-psscriptanalyzer
  rev: v1.0.0
  hooks:
    # Check PowerShell code
    - id: psscriptanalyzer-check-docker
    # Format PowerShell code
    - id: psscriptanalyzer-format-docker

- repo: https://github.com/koalaman/shellcheck-precommit
  rev: v0.9.0
  hooks:
    - id: shellcheck
